### PR TITLE
Add class to class/instance/provider binding tests

### PR DESCRIPTION
**Pull request by jamolkhon**
Following bindings don't work:
- class to class
- class to instance

### CODE REVIEW

**Comment by jamolkhon** [comment]
Sorry about multiple references, I did some rebasing.

**Comment by koriym** [comment]
tests failed ?
https://travis-ci.org/koriym/Ray.Di/jobs/41695080

**Comment by jamolkhon** [comment]
Yes, I added some tests to prove that the above mentioned bindings don't work. I submitted another pull-request that fixes this bug. Should I merge these two pull-requests into one?

**Comment by koriym** [comment]
#90 PR include #89 ? if so no problem, I merge #90.

**Comment by jamolkhon** [comment]
No, #89 and #90 have a common parent. I can rebase #90 on #89, then resubmit.

**Comment by koriym** [comment]
Oh, I merged #90..

**Comment by jamolkhon** [comment]
It's ok. You did right. You can merge #89 too. It has tests, that now all pass.

**Pull request merged**
