### PR TITLE
Feature/add original injector test

### PR DESCRIPTION
**Pull request by koriym**
I add original native injector test to #61 

The second test (testThatAnnotatedSingletonIsNotConstructedMoreThanOnce) is failed also with `original Injector`.

### CODE REVIEW

**Comment by koriym** [comment]
About `SplObjectStorage`, this can be removed after we fix this 'injector' - 'Di Compiler issue' or even now. The `SplObjectStorage` set to in order to get class name in compile error. (instead of number).

**Comment by koriym** [comment]
- @Inject annotation is necessary to have correct configuration.
- the dependency can be singleton, but consumer is created more than one time in compile. (for compile and runtime)
- but singleton dependency is successfully made with both injector.

@craigjbass We have a room to improve, but original issue is solved ?

**Comment by craigjbass** [comment]
> @craigjbass We have a room to improve, but original issue is solved ?

DiCompiler still doesn't work in my codebase but Injector does. (I am not using any DiCompiler incompatible features), so there is still a bug somewhere. Not forgetting my code is very legacy/volatile, and I rely on annotations for as much config as possible.

**Comment by koriym** [comment]
I understood. I also recognized DiCompiler has a problem in more complex object in compile.

**Comment by koriym** [comment]
@craigjbass I merge #65 first. I also would like to merge your "Fix for $isSingleton not containing correct value when using annotate…". If you give me a this PR alone, it would be helpful. Or I can do manually with your credit.

**Comment by koriym** [comment]
@craigjbass I would like to make sure you have an @Inject annotation for constructor. It seems it can be inject without it but binding information is not correct maybe ?

**Pull request closed without merging**
