### PR TITLE
Update doctrine/cache 2.0 and koriym/null-object 1.0

### PR DESCRIPTION
**Pull request by koriym**

### CODE REVIEW

**Comment by 77web** [comment]
I'm waiting for this!!! :pray: :bow:

**Comment by koriym** [comment]
@77web Could you review? LGTU?

**Review by 77web — APPROVED** [review]
Thank you, looks good to me 👍

**Comment by koriym** [comment]
Released. https://github.com/ray-di/Ray.Di/releases/tag/2.12.1

**Pull request merged**
