### PR TITLE
[BC BREAK] Untarget binding is required for concrete class.

### PR DESCRIPTION
**Pull request by koriym**
A concrete class should bind by “untargeting binding“ in module.

This make sure entire object graph is sure and eliminate unbound exception runtime. Also it’s good for the performance.

``` php
 $this->bind(Robot::class);
```

### CODE REVIEW

**Comment by koriym** [comment]
@jamolkhon I would like to hear your comment if possible.

**Comment by jamolkhon** [comment]
How does it improve performance?

Unless class/binding information is cached to permanent storage and then restored on subsequent executions, I don't see any difference. Binding happens a little earlier. But since this is PHP, every request starts from scratch.

Just-in-time bindings work just fine.

On Wednesday Jan 28, 2015 at 11:03 PM, Akihito Koriyama notifications@github.com, wrote:

@jamolkhon I would like to hear your comment if possible.

---

**Comment by jamolkhon** [comment]
It sure helps to identify problems earlier. But I think it should be left as a recommendation, and not a requirement.

**Comment by jamolkhon** [comment]
Guice compatibility is another reason why explicit bindings should not be required for instantiable classes.

**Comment by koriym** [comment]
@jamolkhon Thank you for informative comments, I really appreciate it.

**Comment by koriym** [comment]
> How does it improve performance?

Ray.Di v2 itself does not have cache mechanism unlike Ray.Di v1. I removed it from component. (Ray.Di v1 `CacheInjector` had a doctrine cache) Instead, client save Ray.Di from outside. 

``` php
// save
$injector = new Injector(new AppModule);
$cachedInjector = serialize($injector);
```

Run-time binding works without caching currently .

**Comment by koriym** [comment]
> But I think it should be left as a recommendation, and not a requirement.

 I agree.

**Comment by koriym** [comment]
> Guice compatibility is another reason why explicit bindings should not be required for instantiable classes.

Would you mind explain more about this ? I have no experience with using Guice. :(

**Comment by jamolkhon** [comment]
https://github.com/google/guice/wiki/JustInTimeBindings

**Comment by koriym** [comment]
@jamolkhon thanks for the link.

**Pull request closed without merging**
