### PR TITLE
Adding ability to generate clearer error messages when Unbounds are thrown

### PR DESCRIPTION
**Pull request by tudborg**
When you have very complex dependency chains bound from different modules, it can
be very hard to get an overview of what requires what and where.
When an `Unbound` is thrown, finding the place that required something not yet bound
requires quite a lot of reading.

This PR adds a "stack" to the container that stores the dependencies the container goes through
when calling `getInstance`.
If at some point in the chain, a dependency is not yet bound, this stack will help form the message
for the `Unbound` exception, explaining what needs the class that is unbound.

Here is an example (which can be found in docs/demo/) of one of these exceptions.

```
[00:26:22] ~/src/Ray.Di/docs/demo (2.x-feature/better-error-messages *%)
$> php 12-dependency-chain-error-message.php 
PHP Fatal error:  Uncaught exception 'Ray\Di\Exception\Untargetted' with message 'Ray\Di\Demo\E
 - required by "Ray\Di\Demo\D" (bound to "Ray\Di\Demo\D" with name "" - /home/tbug/src/Ray.Di/docs/demo/src/D.php:5)
 - required by "Ray\Di\Demo\C" (bound to "Ray\Di\Demo\C" with name "" - /home/tbug/src/Ray.Di/docs/demo/src/C.php:5)
 - required by "Ray\Di\Demo\B" (bound to "Ray\Di\Demo\B" with name "" - /home/tbug/src/Ray.Di/docs/demo/src/B.php:5)
 - required by "Ray\Di\Demo\A" (bound to "Ray\Di\Demo\A" with name "" - /home/tbug/src/Ray.Di/docs/demo/src/A.php:5)
' in /home/tbug/src/Ray.Di/src/Container.php:129
Stack trace:
#0 /home/tbug/src/Ray.Di/src/Container.php(80): Ray\Di\Container->unbound('Ray\\Di\\Demmmo\\-)
#1 /home/tbug/src/Ray.Di/src/Arguments.php(58): Ray\Di\Container->getDependency('Ray\\Di\\Demmmo\\-)
#2 /home/tbug/src/Ray.Di/src/Arguments.php(40): Ray\Di\Arguments->getParameter(Object(Ray\Di\Container), Object(Ray\Di\Argument))
#3 /home/tbug/src/Ray.Di/src/NewInstance.php(65): Ray\Di\Arguments->inject(Object(Ray\Di\C in /home/tbug/src/Ray.Di/src/Arguments.php on line 65
```

The inner workings of this framework is still a mystery to me, so I probably missed something cooking this up :)
The wording (specifically terminology) might also need a brush-up.

And thank you for a great framework o/

### CODE REVIEW

**Comment by lorenzo** [comment]
Tests are failing @tbug

**Comment by tudborg** [comment]
Yea.
I also wanted to move the debug string out of `__tostring` and into something like `getDebugInfo` that some of the other classes also have.

 I'll make the tests pass tonight o/

**Comment by koriym** [comment]
@tbug @lorenzo 
I recognize the room to improve the clary for the unbound error. Thank you for the PR.
Quick reminder: Unbound exception is chained with $e->getPrevious(); please consider this also with your stack method. Thanks.

**Comment by tudborg** [comment]
Hey @koriym 
I'm not entirely sure what you mean by

>  Unbound exception is chained with $e->getPrevious(); please consider this also with your stack method

Please clarify :-)
What would you like me to change?

**Comment by koriym** [comment]
If we catch `Unbound exception` and handle it as follows,

``` php
try {
    $injector->getInstance(A::class);
} catch (\Exception $e) {
    do {
        echo sprintf( "%s:%s\n", get_class($e), $e->getMessage());
        $e = $e->getPrevious();
    } while ($e);
}
```

Output is like this.

```
php docs/demo/12-dependency-chain-error-message.php 

Ray\Di\Exception\Unbound:dep (Ray\Di\Demo\B-)
Ray\Di\Exception\Unbound:dep (Ray\Di\Demo\C-)
Ray\Di\Exception\Unbound:dep (Ray\Di\Demo\D-)
Ray\Di\Exception\Unbound:dep (Ray\Di\Demo\E-)
Ray\Di\Exception\Untargetted:Ray\Di\Demo\E
```

We can see `$e` is already "stacked" (chained) without own stack implementation.

Hope this clarify the difference of original (stacking exception) and yours (stack dependency and use it when exception thrown).

**Comment by koriym** [comment]
Your exception message is nice, I like it.
@lorenzo @mackstar I would like to hear your thought for it.

**Comment by tudborg** [comment]
Ah. I see your point.
Use the exception message itself to carry the dependency help message to the top.
It will def. be a lot cleaner than stacking dependency information in the container.
I'll have a hack at it.

**Comment by tudborg** [comment]
Okay, looked a bit at this.
PHP (at least my installation) only outputs the deepest exception in a chain if oncought.
This makes using the exception chain for a good message a non-optimal aproach imo.
But I also understand that stacking dependencies in the Container is a bit messy.
I'll continue experimenting with a better way.

**Comment by tudborg** [comment]
Did a few experiments but they all turned out worse than the current PR.
We could avoid building a dependency stack on the Container if we inspected the `debug_backtrace()`.
From that, We could create good error messages on all Unbounds, but it seems like a dirty way to do it.

To clarify what my goal is here:
Ideally, all Unbound messages should contain information about the entire dependency chain.
Alternatively (as in this PR), at least the deepest Unbound should contain the full stack information, as that is what PHP writes to the console when you encounter an unhandled exception, and what most people would inspect in a logging system.

But if everyone is okay with inspecting the `debug_backtrace` it would be trivial to create some good error messages in all Unbounds.

**Comment by koriym** [comment]
> be a lot cleaner than stacking dependency information in the container.

That is a point !

> PHP (at least my installation) only outputs the deepest exception in a chain if oncought.

Yes, The exception chain is only shown with Xdebug.

> To clarify what my goal is here:
> Ideally, all Unbound messages should contain information about the entire dependency chain.
> Alternatively (as in this PR), at least the deepest Unbound should contain the full stack information, as that is what PHP writes to the console when you encounter an unhandled exception, and what most people would inspect in a logging system.

Thank you for the clarify. Nice summary.

**Comment by koriym** [comment]
> But if everyone is okay with inspecting the debug_backtrace it would be trivial to create some good error messages in all Unbounds.

Using `debug_backtrace` is handy, But I guess it makes fragile code ?

**Comment by lorenzo** [comment]
I agree that using `debug_backtrace` could make that piece of code a bit fragile, as any extra calls added to the stack would potentially break the implementation.

@tbug What about instead of using the exception _message_ to  carry the state to the top, you introduced a property and a getter/setter in the exception class. Those can be used to store some state that can be transmitted to the next call

**Comment by tudborg** [comment]
@lorenzo I was thinking that as well, but it still doens't allow a nice message for the deepest exception.
I'd like to see the deepest exception knowing about the entire chain of dependencies.
To do that, we either have to send information down as we get deeper, or inspect the backtrace.

Also, inspecting the `debug_backtrace` won't be _that_ fragile, as we would specifically look for calls to
`getDependency`, nothing else. So any calls in between won't matter.
The only think that will break it, is if `getDependency` suddely changes name.

Passing the chain information down is def. cleaner, but will require changing a lot of public functions, which I'd really like to avoid.
Using `debug_backtrace` requires no changes to function signatures, but would be less easy to understand and debug if something goes wrong.

**Comment by koriym** [comment]
> Also, inspecting the debug_backtrace won't be that fragile, 

@tbug Ok. May I review your code ?

**Comment by tudborg** [comment]
I'll give it some work this weekend o/

**Comment by koriym** [comment]
@tbug Thanks. Arigato.

**Comment by tudborg** [comment]
There you go.
I rushed it a bit, as I am kind of busy atm.
The tests pass on my machine. Hopefully they'll pass CI as well.

**Comment by koriym** [comment]
@tbug thanks ! I will review it.

**Comment by koriym** [comment]
@tbug I still think about using `exception`, modify with your code.
Additionally, the score of scrutinizer quality index drop, I know it's bit extreme, But I would like to keep 10.0 as past and another my package.
https://scrutinizer-ci.com/g/ray-di/Ray.Di/inspections/b9720883-a98e-40c0-a95b-b7c277831c8c

**Comment by tudborg** [comment]
You can't accomplish what I'd like to see with exceptions alone.
I'd like for the innermost exception to contain the entire dependency stack that failed.
That is not possible without passing some dependency information down the chain (which is kind of what I did with the dependency stack I did)
You can ofc. do that, but it requires a lot of changes to function signatures without much benefic other than extra debug info.
That seems like a violent change to me, compares to the benefits.

Alternatively, you need to catch the unbound exception at say, `getInstance`, use the exception chain to build a nice message and throw a completely new exception, throwing away the exception chain. (as PHP only shows the inner-most exception per default, the innermost exception _must_ contain the nicer error message to be useful)

**Comment by koriym** [comment]
@tbug @lorenzo I pushed  "Exception" version.

If you `echo` caught `$e`, Output is like follows.

```
$ php docs/demo/12-dependency-chain-error-message.php 
exception 'Ray\Di\Exception\Untargetted' with message 'Ray\Di\Demo\E' in /Users/akihito/git/Ray.Di/src/Container.php
- required by Ray\Di\Demo\B with name "" in /Users/akihito/git/Ray.Di/docs/demo/src/A.php:7
- required by Ray\Di\Demo\C with name "" in /Users/akihito/git/Ray.Di/docs/demo/src/B.php:7
- required by Ray\Di\Demo\D with name "" in /Users/akihito/git/Ray.Di/docs/demo/src/C.php:7
- required by Ray\Di\Demo\E with name "" in /Users/akihito/git/Ray.Di/docs/demo/src/D.php:7
```

**Comment by tudborg** [comment]
Ah. I understand what you mean now.
Although doing it this way, the wording needs to be different to read nicely.
Also, the list of requires (`- required ....`) should, to me at least, be reversed.
So you can read it from the top, down.

In my mind, a clear message would (loosly formattet) read something like:

Exception Untargetted E
required by D
required by C
required by B

But I like your exception chaining way better then `debug_backtrace` !

I'll update my PR to show you what I mean.

**Comment by tudborg** [comment]
Changed the wording a bit, but apart from that, it's pretty much the same.
An exception now reads

```
[16:33:09] ~/src/Ray.Di (2.x-feature/better-error-messages *=)
$> php docs/demo/12-dependency-chain-error-message.php
PHP Fatal error:  Uncaught exception 'Ray\Di\Exception\Untargetted' with message 'Ray\Di\Demo\E'
- dependency "Ray\Di\Demo\E" with name "" used in /Users/tbug/src/Ray.Di/docs/demo/src/D.php:7
- dependency "Ray\Di\Demo\D" with name "" used in /Users/tbug/src/Ray.Di/docs/demo/src/C.php:7
- dependency "Ray\Di\Demo\C" with name "" used in /Users/tbug/src/Ray.Di/docs/demo/src/B.php:7
- dependency "Ray\Di\Demo\B" with name "" used in /Users/tbug/src/Ray.Di/docs/demo/src/A.php:7
```

**Comment by koriym** [comment]
@tbug  Using `'` (single quotation)  is more php standard style message than `"` ? 

```
 - dependency 'Ray\Di\Demo\E' with name '' used in /Users/tbug/src/Ray.Di/docs/demo/src/D.php:7
```

**Comment by tudborg** [comment]
@koriym Yes, true. Didn't consider that.

**Comment by koriym** [comment]
How about to add `$e->getTraceAsString()` to error message on the end like standard php exception message ?

**Comment by tudborg** [comment]
Now looks like this.

```
$> php docs/demo/12-dependency-chain-error-message.php
exception 'Ray\Di\Exception\Untargetted' with message 'Ray\Di\Demo\E'
- dependency 'Ray\Di\Demo\E' with name '' used in /Users/tbug/src/Ray.Di/docs/demo/src/D.php:7
- dependency 'Ray\Di\Demo\D' with name '' used in /Users/tbug/src/Ray.Di/docs/demo/src/C.php:7
- dependency 'Ray\Di\Demo\C' with name '' used in /Users/tbug/src/Ray.Di/docs/demo/src/B.php:7
- dependency 'Ray\Di\Demo\B' with name '' used in /Users/tbug/src/Ray.Di/docs/demo/src/A.php:7

#0 /Users/tbug/src/Ray.Di/src/Arguments.php(40): Ray\Di\Arguments->getParameter(Object(Ray\Di\Container), Object(Ray\Di\Argument))
#1 /Users/tbug/src/Ray.Di/src/NewInstance.php(65): Ray\Di\Arguments->inject(Object(Ray\Di\Container))
#2 /Users/tbug/src/Ray.Di/src/Dependency.php(69): Ray\Di\NewInstance->__invoke(Object(Ray\Di\Container))
#3 /Users/tbug/src/Ray.Di/src/Container.php(76): Ray\Di\Dependency->inject(Object(Ray\Di\Container))
#4 /Users/tbug/src/Ray.Di/src/Arguments.php(58): Ray\Di\Container->getDependency('Ray\\Di\\Demo\\B-')
#5 /Users/tbug/src/Ray.Di/src/Arguments.php(40): Ray\Di\Arguments->getParameter(Object(Ray\Di\Container), Object(Ray\Di\Argument))
#6 /Users/tbug/src/Ray.Di/src/NewInstance.php(65): Ray\Di\Arguments->inject(Object(Ray\Di\Container))
#7 /Users/tbug/src/Ray.Di/src/Dependency.php(69): Ray\Di\NewInstance->__invoke(Object(Ray\Di\Container))
#8 /Users/tbug/src/Ray.Di/src/Container.php(76): Ray\Di\Dependency->inject(Object(Ray\Di\Container))
#9 /Users/tbug/src/Ray.Di/src/Container.php(58): Ray\Di\Container->getDependency('Ray\\Di\\Demo\\A-')
#10 /Users/tbug/src/Ray.Di/src/Injector.php(47): Ray\Di\Container->getInstance('Ray\\Di\\Demo\\A', '')
#11 /Users/tbug/src/Ray.Di/docs/demo/12-dependency-chain-error-message.php(33): Ray\Di\Injector->getInstance('Ray\\Di\\Demo\\A')
#12 {main}
```

**Comment by koriym** [comment]
@tbug Thanks. I'ill going to merge. Please wait for a while. Thank you for your patience.

**Comment by koriym** [comment]
I release as [2.2.1](https://github.com/ray-di/Ray.Di/releases/tag/2.2.1).

Thank your for your hard work and patience @tbug !

> And thank you for a great framework o/

and the compliment :)

**Pull request merged**
