### PR TITLE
Unit Test for Issue 48. 

### PR DESCRIPTION
**Pull request by craigjbass**
Ray.Di doesn't seem to like provider definitions for abstract classes 
- line 361 \Ray\Di\Injector

### CODE REVIEW

**Comment by koriym** [comment]
@craigjbass I need confirmation.

As Travis told us, the error is `NotBound`

 "Ray\Di\Exception\NotBound: Valid interface is not found. (array ?) Injection requested at argument #0 $config in Ray\Di\Mock\AbstractClassWithConstructor constructor"
https://travis-ci.org/koriym/Ray.Di/jobs/17651119

and yes this `$config` seems no binding.
https://github.com/craigjbass/Ray.Di/blob/ad362ce95d7720b8f7ec454abea8f2f32f056f26/tests/Ray/Di/Mock/AbstractClassWithConstructor.php#L8

something wrong / misunderstanding  ?

**Comment by craigjbass** [comment]
AbstractClassWithConstructor has a binding, look at the ConstructorModule.

The bug is related to binding a provider to an abstract class.

If you make AnstractClassWithConstructor not abstract the tasty case passes.

**Comment by craigjbass** [comment]
Test*

**Comment by koriym** [comment]
@craigjbass Sorry my _easy_ misunderstood.

The problem was `abstract class` binding is not handle correctly.

**Pull request merged**
